---
- name: Create the OpenStack resources for cluster installation
  import_playbook: provision_resources.yml

- hosts: bm_app
  become: no
  gather_facts: no
  tasks:
  - name: Update the port binding host id to match its ip
    command: python update_binding_host_id.py {{ inventory_hostname }}
    delegate_to: localhost
    retries: 10
    register: update_port
    until: update_port is succeeded

# NOTE(shadower): Bring in the host groups:
- name: evaluate groups
  import_playbook: ../../init/evaluate_groups.yml


- name: Wait for the nodes and gather their facts
  any_errors_fatal: true
  hosts: oo_all_hosts
  become: yes
  # NOTE: The nodes may not be up yet, don't gather facts here.
  # They'll be collected after `wait_for_connection`.
  gather_facts: no
  tasks:
  - name: Wait for the the nodes to come up
    wait_for_connection:

  - name: Gather facts for the new nodes
    setup:

- hosts: bm_app
  become: no
  gather_facts: no
  tasks:
  - name: Wait for cloud-init to finish
    command: systemctl show cloud-init --property SubState,ActiveState
    become: yes
    retries: 10
    register: result
    ignore_errors: yes
    until: ('ActiveState=active' in result.stdout) and ('SubState=exited' in result.stdout)

  - name: Wait until the host runs the neutron agent
    command: python agents.py {{ inventory_hostname }}
    delegate_to: localhost
    retries: 10
    register: agent_list
    until: agent_list is succeeded

  - name: Update the port
    os_port:
      state: present
      name: "{{ kubelet_port_name }}"
      device_owner: compute:shiftstack
    delegate_to: localhost

# TODO(shadower): consider splitting this up so people can stop here
# and configure their DNS if they have to.
- name: Populate the DNS entries
  any_errors_fatal: true
  hosts: localhost
  tasks:
  - name: Populate DNS entries
    import_role:
      name: openshift_openstack
      tasks_from: populate-dns.yml
    when:
    - openshift_openstack_external_nsupdate_keys is defined
    - openshift_openstack_external_nsupdate_keys.private is defined or openshift_openstack_external_nsupdate_keys.public is defined


- import_playbook: ../../init/basic_facts.yml

- name: Optionally subscribe the RHEL nodes
  any_errors_fatal: true
  hosts: oo_all_hosts
  become: yes
  gather_facts: yes
  tasks:
  - name: Subscribe RHEL instances
    import_role:
      name: rhel_subscribe
    when:
    - ansible_distribution == "RedHat"
    - rhsub_user is defined
    - rhsub_pass is defined

- name: Show information about the deployed cluster
  import_playbook: cluster-info.yml
